### ISSUE TITLE
IGNITE logo

### ISSUE THREAD

**Issue by graciellehigino** [graciellehigino/IGNITE#5]
**[why?]** It is important to have a visual identity that will identify IGNITE and everything made in this project. The IGNITE logo will represent its ideals, unite collaborators and contributors, and inspire whoever sees it.

**[how?]** You can help by brainstorming here in the comments or sharing your designs with us.

**[what?]** We need a logo to put on our material and help spread IGNITE through the web.

**Comment by vektorious** [comment]
I already like the one you used for [Mozilla Pulse](https://assets.mofoprod.net/network-pulse/images/entries/2018-04-07_233215.4947050000.png).

Maybe you could go from there? Or are you looking for something completely new?

**Comment by graciellehigino** [comment]
Thank you, @vektorious ! I can go from there, but I just don't have the skills to draw something prettier. I was thinking of using the fire *per se* or something like sparks, lightning...
Thank you so much for your feedback!

**Comment by vektorious** [comment]
Can you upload the file you already have? Maybe as a .svg? 

If nobody starts designing one before I can try my best during the mozilla global sprint 🔥 

But I am not good at this either but maybe I can provide a intermediate solution 😉

**Comment by graciellehigino** [comment]
Sure! I uploaded the file in MEGA provisionally: [https://mega.nz/#!ASojXYLC!4-n9E7oL30ZAc0AshCUzDCtg2zHKgP1peEgij1FFnJc](https://mega.nz/#!ASojXYLC!4-n9E7oL30ZAc0AshCUzDCtg2zHKgP1peEgij1FFnJc). Thank you so much for your help! ❤️

**Comment by taisdesouzalessa** [comment]
@graciellehigino here are 2 options of logo, with 2-3 colors and 1 color:
<img width="785" alt="image" src="https://user-images.githubusercontent.com/22157921/39898689-b9951abe-546c-11e8-9b77-f9edb337f6d5.png">


The fonts used are in Google Fonts:
[Roboto (Bold)](https://fonts.google.com/specimen/Roboto)
[Saira (Bold)](https://fonts.google.com/specimen/Saira)

.eps file [here](https://drive.google.com/open?id=1ZxODEUplEoi9H7nC0njaNfDtPzC8kHC0) - let me know if you need any other format :)

**Comment by vektorious** [comment]
Oh cool! I think I would prefer the left one because of its simplicity

**Comment by RaoOfPhysics** [comment]
@taisdesouzalessa: These are beautiful! Well done! :D

**Comment by vektorious** [comment]
@taisdesouzalessa could you upload .png versions of the left design? Then I can try and implement it into the website

**Comment by graciellehigino** [comment]
OMG 😲 those are awesome! I can't pick one, I need help! I **love** roboto, but I really liked the left one, too. Thank you SO MUCH, @taisdesouzalessa !! ❤️ 
Can you upload in .svg? I have serious problems with .eps in my computer. ]=

**Comment by marcosvital** [comment]
Wow, those are amazing, @taisdesouzalessa !

@graciellehigino , I love how the original logo reminds us about Sagan's metaphor about Science as a 'candle in the dark'.
Looking on all the amazing logos made by Tais from this perspective, I like how the first set still remind us of a candle.
On the other hand, the second set with the little flame is also pretty cool, and I feel that it gives a strong visual identity for the project!

I wouldn't know which one to choose... 😄

**Comment by alexbrunops** [comment]
holly molly, those are awesome! Really liked the left ones, but also liked the all caps. Congrats @taisdesouzalessa, really nice job! (:

**Comment by taisdesouzalessa** [comment]
@graciellehigino - here are the .svg files
[svg.zip](https://github.com/graciellehigino/IGNITE/files/2001986/svg.zip)

@vektorious - here are the .png files
[png.zip](https://github.com/graciellehigino/IGNITE/files/2001988/png.zip)

Let me know if you run into any problems accessing those :)
